# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: novakiosk-os
description: Basic Fedora Sway installation with required packages for supporting novakiosk and novakeys.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /
      - source: etc/greetd/config.toml
        destination: /etc/greetd/config.toml

  - type: dnf
    install:
      packages:
        - sway
        - xorg-x11-server-Xwayland
        - gcc-c++
        - gtk4-layer-shell
        - NetworkManager-tui
        - openssl
        - openssl-devel
        - wayvnc
        - ydotool
        - openssh-server
        - greetd
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: systemd
    system:
      enabled:
        - NetworkManager.service
        - sshd.service
        - ydotool.service
        - greetd.service
        - cups.service

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
      - scope: user

  - type: signing
